### ISSUE TITLE
Does not work with older maps

### ISSUE THREAD

**Issue by MatheusBarbosa22** [FrankTheBoxMonster/LoL-MAPGEO-Converter#9]
Just doesn't work with older maps.

I tested it so many times, and when i put it on blender, can only see the silhouette of the map
showing only a "constellation" of vertices

![only vertices](https://user-images.githubusercontent.com/98568806/151477832-bc642cc4-4d52-4c37-9e22-4df1a1f0e332.jpg)

this is the old winter map

**Comment by FrankTheBoxMonster** [comment]
Which map exactly are you trying to convert?

SR was migrated to .mapgeo in March 2019.  The winter of that year is when the dragon rifts were added, which has been cited by Riot as the reason why we haven't gotten a winter SR map since.  So whatever "old winter map" you are trying to convert cannot have possibly come from Riot, unless you are trying to use a .wgeo or .nvr file, which are not supported by the converter since they are a completely different file type.

**Comment by MatheusBarbosa22** [comment]
Oh, understood

So you don't know any other way to convert this type of file?
I've testing it for such time ;-; worked very well with tft map

the geometry of this arcaic work is hard to understand...

**Comment by FrankTheBoxMonster** [comment]
Well you didn't answer where you got the file from or what type it is, so I'm not sure how to convert it, but if it's a different file type then you should look for something that actually converts that file type.

**Comment by MatheusBarbosa22** [comment]
It's from killerskins.com
https://killerskins.com/thekillerey/mods/maps/old-summoners-rift/old-winter-rift-2011/

![Screenshot_1](https://user-images.githubusercontent.com/98568806/151682752-8c6ce411-68b3-466f-ad82-e8faf1eda520.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/98568806/151682777-94805404-784b-4496-b6c3-f1ce72c32f27.jpg)

**Comment by MatheusBarbosa22** [comment]
I downloaded it. its a .fantome extractible file, that contains the .wad file that can be extracted the .mapgeo file from it

**Comment by FrankTheBoxMonster** [comment]
So there's multiple issues here.

Mod files are not guaranteed to be as "correct" as Riot files.  In this case, the mod file is missing vertex normals, which the converter spits out several errors over.  I can modify the converter to ignore normals, but there can be some issues with polygons facing the wrong way without them.  This is an issue with the map's creator and not something that can be fixed by the converter.

Another issue is that the Worlds.mapgeo file appears to have several broken faces, but might also not actually be used by the mod and just included for no reason.  Base_SRX.mapgeo appears to be fine in this regard.

Last issue is that older maps typically used a lot of blended and decal textures, which without special shaders will look extremely broken when converted.  This is again not something that can be fixed by the converter, since fixing that will change completely depending on which program you load the file in.

I've updated the converter with the version that can work without vertex normals, but due to the other issues listed, this will only be able to get you so far without having to do some manual cleanup work inside of Blender or whatever other program.  New version can be found [here](https://github.com/FrankTheBoxMonster/LoL-MAPGEO-Converter/releases/tag/v2.5).

**Comment by MatheusBarbosa22** [comment]
oh, ok, understood

well, by first, thank you for try to fix it
i tried again and the map is ok

and as you said, it's really hard to apply all the textures in the materials due to
immense amount of non merged faces. a very big mess

anyway, i just wish i could edit the file in blender. now i can
thanks to you

Now I'm going to decide whether to pack it all up or not
hahahha

**Comment by MatheusBarbosa22** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/98568806/151724114-96aacbf7-f62a-45dd-94ce-9ccbb58a48f8.jpg)

**Comment by TheKillerey** [comment]
> So there's multiple issues here.
> 
> Mod files are not guaranteed to be as "correct" as Riot files. In this case, the mod file is missing vertex normals, which the converter spits out several errors over. I can modify the converter to ignore normals, but there can be some issues with polygons facing the wrong way without them. This is an issue with the map's creator and not something that can be fixed by the converter.
> 
> Another issue is that the Worlds.mapgeo file appears to have several broken faces, but might also not actually be used by the mod and just included for no reason. Base_SRX.mapgeo appears to be fine in this regard.
> 
> Last issue is that older maps typically used a lot of blended and decal textures, which without special shaders will look extremely broken when converted. This is again not something that can be fixed by the converter, since fixing that will change completely depending on which program you load the file in.
> 
> I've updated the converter with the version that can work without vertex normals, but due to the other issues listed, this will only be able to get you so far without having to do some manual cleanup work inside of Blender or whatever other program. New version can be found [here](https://github.com/FrankTheBoxMonster/LoL-MAPGEO-Converter/releases/tag/v2.5).
The mapgeo converter by Crauzer does not work correctly with Mapgeos. My maps have correct normals and vertices.
